// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTozhBmMF0ILum4wPVMfGP098Yr_QqLc',
    appId: '1:933061962046:web:a26700de5f9b867d25a46f',
    messagingSenderId: '933061962046',
    projectId: 'travel-journal-app-360ac',
    authDomain: 'travel-journal-app-360ac.firebaseapp.com',
    storageBucket: 'travel-journal-app-360ac.appspot.com',
    measurementId: 'G-DD8M5KP46J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFE_gXxgPote-HUN7UK6Vu9zz-h6KsWc',
    appId: '1:933061962046:android:b73715c8c4982ddb25a46f',
    messagingSenderId: '933061962046',
    projectId: 'travel-journal-app-360ac',
    storageBucket: 'travel-journal-app-360ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvhbD13_DvyRdgGeLEZPckZMgtaduIbI',
    appId: '1:933061962046:ios:12b4995e900c33fb25a46f',
    messagingSenderId: '933061962046',
    projectId: 'travel-journal-app-360ac',
    storageBucket: 'travel-journal-app-360ac.appspot.com',
    iosBundleId: 'com.example.travelJournel',
  );
}
